language: ruby
rvm:
  - ruby-head
  - 2.1.0
  - 2.0.0
  - 1.9.3
  - jruby-head
  - jruby-19mode
  - rbx
matrix:
  allow_failures:
    - rvm: rbx
    - rvm: jruby-head
before_install: gem install bundler
script:
  - bundle exec rake
  - cd spec/integration/rails && ./test-against-several-rails-versions.sh
