language: ruby
rvm:
  - ruby-head
  - 2.1
  - 2.0.0
  - jruby-head
  - rbx-2
matrix:
  allow_failures:
    - rvm: rbx-2
    - rvm: jruby-head
before_install: gem install bundler
script:
  - bundle exec rake
  - cd spec/integration/rails && ./test-against-several-rails-versions.sh
